name: CI
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - 'main'
jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - uses: hashicorp/setup-terraform@v3
      with:
        # This setting is necessary to avoid errors during doc generation.  See https://github.com/hashicorp/terraform-plugin-docs/issues/127
        terraform_wrapper: false

    - uses: actions/checkout@v4

    - name: Run doc generation
      id: doc_gen
      run: |
        make docs && echo "uncommitted_files=$(git status --porcelain ./docs ./examples | wc -l)" >> $GITHUB_OUTPUT

    - name: Show uncommitted changes
      if: ${{ steps.doc_gen.outputs.uncommitted_files != 0 }}
      run:
        echo "Found uncommitted doc changes"
        git status --porcelain ./docs ./examples

    - name: Uncommitted changes check
      if: ${{ steps.doc_gen.outputs.uncommitted_files != 0 }}
      uses: actions/github-script@v7
      with:
        script: |
          core.setFailed('tfplugindocs generated uncommitted doc changes. Please run 'make docs' and add doc changes to your commits.')

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - uses: actions/checkout@v4

    - name: Build
      run: |
        make build

  # run acceptance tests in a matrix with Terraform core versions
  terraform-acceptance-test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      max-parallel: 1 # need to run one at a time to avoid conflicts
      matrix:
        # Test with min and max supported Terraform versions
        terraform:
          - '1.5.3'
          - '1.12.1'
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - uses: actions/checkout@v4

    - name: Run tests
      timeout-minutes: 15
      env:
        ASTRA_API_TOKEN: ${{ secrets.TEST_ASTRA_API_TOKEN }}
        TF_ACC: "1"
        TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
      run: |
        make testacc
