name: Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.16.2'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go mod download

    - name: Install tfplugindocs
      run: |
        go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs

    - name: Run doc generation
      id: doc_gen
      run: |
        tfplugindocs && echo "::set-output name=local_changes::$(git status --porcelain ./docs | wc -l)"

    - name: Uncommitted changes Check
      if: ${{ steps.doc_gen.outputs.local_changes != 0 }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('tfplugindocs generated uncommitted doc changes. Please run tfplugindocs and add doc changes to your commits.')

    - name: Build
      run: |
        go build -v .

  # run acceptance tests in a matrix with Terraform core versions
  test:
    name: Matrix Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - '0.12.29'
          - '0.13.4'
          - '0.14.0-beta2'
          - '0.15.0-dev'
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.16.2'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go mod download
        
    - name: TF acceptance tests
      timeout-minutes: 10
      env:
        TF_ACC: "1"
        TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
      run: |
        go test -v -cover ./internal/provider/