name: CI
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'

    - uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go mod download

    - name: Install tfplugindocs
      run: |
        go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs

    - name: Run doc generation
      id: doc_gen
      run: |
        tfplugindocs && echo "::set-output name=local_changes::$(git status --porcelain ./docs | wc -l)"

    - name: Uncommitted changes Check
      if: ${{ steps.doc_gen.outputs.local_changes != 0 }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('tfplugindocs generated uncommitted doc changes. Please run tfplugindocs and add doc changes to your commits.')

    - name: Build
      run: |
        go build -v .

  # run acceptance tests in a matrix with Terraform core versions
  terraform-acceptance-test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      max-parallel: 1
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          # - '0.15.5'
          - '1.4.6'
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'

    - uses: actions/checkout@v3

    - name: Run tests
      timeout-minutes: 15
      env:
        ASTRA_API_TOKEN: ${{ secrets.TEST_ASTRA_API_TOKEN }}
        TF_ACC: "1"
        TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
      run: |
        make testacc
